Add "-f" to the /move command
MCCTeam/Minecraft-Console-Client pull request #1874
Opened 2021-12-27 21:21 UTC by Daenges

As a solution for #1872 I have implemented a `-f` argument, which forces the movement regardless of its potential consequences.

2021-12-28 09:58 UTC, ORelio requested changes
Looks good! However, please document that the switch exists in command help or error message when path is unsafe, otherwise nobody will know about it.

2021-12-28 10:39 UTC, Daenges commented
@ORelio Changes applied.

2021-12-28 12:24 UTC, ReinforceZwei reviewed
How about also applying the `force` option for moving to absolute coordinate?

2021-12-28 12:24 UTC, ReinforceZwei commented on MinecraftClient/Commands/Move.cs
> +        public override string CmdUsage { get { return "move <on|off|get|up (-f)|down (-f)|east (-f)|west (-f)|north (-f)|south (-f)|x y z>"; } }
I think the help message here became too complex and hard to read. 

How about:
```suggestion
        public override string CmdUsage { get { return "move <on|off|get|up|down|east|west|north|south|x y z> [-f]"; } }
```

2021-12-28 12:24 UTC, ReinforceZwei commented on MinecraftClient/Commands/Move.cs
> +        public override string CmdDesc { get { return "walk or start walking. Included protection can be bypassed with \"-f\"."; } }
```suggestion
        public override string CmdDesc { get { return "walk or start walking. Unsafe path protection can be bypassed with \"-f\"."; } }
```

2021-12-28 12:24 UTC, ReinforceZwei commented on MinecraftClient/Commands/Move.cs
> +            string[] args = getArgs(command.ToLower());
I think the parsing of the arguments could be done like below:
https://github.com/MCCTeam/Minecraft-Console-Client/blob/259ef80cf97b18a55da0f4b810460e1e49e1711a/MinecraftClient/Program.cs#L63-L71

We look for `-f` in the whole argument string, if found, set a boolean flag to true and remove the `-f` from the argument string. Then the position of `-f` will no longer be important, and could be easily apply the flag to moving with absolute coordinate.

2021-12-28 13:16 UTC, Daenges commented
> How about also applying the `-f` option for moving with absolute coordinate?

@ReinforceZwei 
Also thought about that. The only problem here is, that the absolute movement consists of several individual movement desicions. I do not think that players can actually estimate what happens, if the client goes on full risk on every movement. This can result in major damage, since the behaviour of the client on the way can result in unpredictable dangerous situations. (Especially problematic since you can not stop the movement of the client without disconnecting.)

My idea is that the player lets the bot autowalk **near** a dangerous situation and then switches to direct control. Thereby we force the user to be attentive and to be responsible of their own decisions.

2021-12-28 13:54 UTC, Daenges commented
Despite my doubts I implemented the changes. Lets pray for the peoples common sense.

2021-12-28 14:43 UTC, ReinforceZwei commented
That could be a problem for those who don't pay attention to the situation. Maybe forcing people to type the full `-force` argument could raise some attention? 

Never mind if you don't like unleashing unsafe path for absolute coordinate. Feel free to revert it back.

2021-12-28 14:52 UTC, Daenges commented
I thought about git and how it also allows the -f command without any further barricades.

As long as people use the regular command, they get warned by a message and everything further they do is on their own responsibility.

Why restrict their freedom if they know what they want to do? Some need to touch the fire to know that it is hot.

2021-12-28 17:29 UTC, ORelio reviewed
Looks good to me! Here are a few additional suggestions mainly to improve wording/readability:

2021-12-28 17:29 UTC, ORelio commented on MinecraftClient/Commands/Move.cs
> +        public override string CmdDesc { get { return "walk or start walking. Included protection can be bypassed with \"-f\"."; } }
```suggestion
        public override string CmdDesc { get { return "walk or start walking. \"-f\": force unsafe movements like falling or touching fire"; } }
```

2021-12-28 17:29 UTC, ORelio commented on MinecraftClient/Commands/Move.cs
> +                        else return !takeRisk ? Translations.Get("cmd.move.suggestforce") : Translations.Get("cmd.move.fail", goal);
How about removing the negation in ternary condition and also include coordinates:
```suggestion
                        else return takeRisk ? Translations.Get("cmd.move.fail", goal) : Translations.Get("cmd.move.suggestforce", goal);
```
(see below for coordinates in message)

2021-12-28 17:29 UTC, ORelio commented on MinecraftClient/Resources/lang/en.ini
> +cmd.move.suggestforce=The implemented protection prevents a movement in this direction. Use the -f parameter to force the movement.
The path either does not exists _or_ is unsafe. So the message could look like this instead:
```suggestion
cmd.move.suggestforce=Failed to compute a safe path to {0}. Try -f parameter to allow unsafe movements.
```

2021-12-28 17:29 UTC, ORelio commented on MinecraftClient/Resources/lang/de.ini
> +cmd.move.suggestforce=Die implementierte Absicherung verhindert eine Bewegung in diese Richtung. Du kannst sie mit dem -f Parameter erzwingen.
I cannot make suggestions in German but see the English version below.

2021-12-28 17:36 UTC, ORelio approved these changes

2021-12-28 17:39 UTC, ORelio commented
Good job! I'll leave @ReinforceZwei review again just in case and it should be good to merge 👍

2021-12-29 06:46 UTC, ReinforceZwei commented on MinecraftClient/Commands/Move.cs
> +                        else return !takeRisk ? Translations.Get("cmd.move.suggestforce") : Translations.Get("cmd.move.dir_fail");
```suggestion
                        else return takeRisk ? Translations.Get("cmd.move.dir_fail") : Translations.Get("cmd.move.suggestforce");
```

2021-12-29 14:34 UTC, merged